### ISSUE TITLE
Add spacing above footer on blog

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/rad-new#103]
http://live-rad-new.pantheonsite.io/blog

Kien's design has the Ready To Talk/Send a Message pretty far below the Load More button on desktop (looks great on tablet and mobile). Would love to move the footer area up 250px closer to the Load More button (on desktop only), with the understanding that the red box will overlap with the diagonal line.

**Comment by jselt** [comment]
I believe @cfox612 just did this

**Comment by daniellerad** [comment]
Has it just not been pushed live yet? Not seeing it.
