### ISSUE TITLE
e-Newsletter

### ISSUE THREAD

**Issue by cfox612** [radcampaign/rad-new#124]
Create/theme newsletter region/block.

![rad-home-rd1-v1-11](https://user-images.githubusercontent.com/2796676/50646134-55e7f080-0f43-11e9-8813-cd8246c3c96c.jpg)

**Comment by kristinsj** [comment]
@jselt this is the initial piece. @cfox612 anything to relay?

**Comment by cfox612** [comment]
There's a "newsletter" branch with the styles and some mailchimp code. I think it's just missing a "thanks" message after submitting (Allyson verified it work I believe last week).

**Comment by jselt** [comment]
Got it - thanks!

**Comment by jselt** [comment]
@cfox612 so the form doesn't work - hence the the welcome email not getting sent - did you use Mailchimp's formbuilder to generate the code?

Just wondering if it spit out some wrong code maybe.

**Comment by cfox612** [comment]
Yes, the "condensed" code maybe? One of the ones from the list it spit out for the non-profit list.

**Comment by jselt** [comment]
k - I'll try and regenerate it with their formbuilder
