### ISSUE TITLE
Fix plus sign on homepage mobile (android)	

### ISSUE THREAD

**Issue by kristinsj** [radcampaign/rad-new#134]
https://radcampaign.com/	
The first plus sign on the site runs into the text.

**Comment by kristinsj** [comment]
just noticed: "Possibly fixed in newsletter multidev."

**Comment by jselt** [comment]
This looks fine on my phone on Chrome and in Chrome's responsive emulator - but maybe Justyn should check before we close (I assume she reported it)

**Comment by kristinsj** [comment]
Justyn checked - all set.
