### ISSUE TITLE
Do related blogs exclude the blog a user is on?

### ISSUE THREAD

**Issue by kristinsj** [radcampaign/rad-new#135]
Justyn was on the Elon Musk blog post - https://radcampaign.com/blog/what-i-learned-elon-musk-and-biggest-tech-ceos - and noticed the first suggested blog post is the Elon Musk post the user is on. Is there a way to exclude?

**Comment by jselt** [comment]
I fixed that last week

**Comment by kristinsj** [comment]
k!
