### ISSUE TITLE
Authors/Staff

### ISSUE THREAD

**Issue by cfox612** [radcampaign/rad-new#21]
Fields:

- Name (text field)
- First Name (text field)
- Last Name (text field)
- Title (textfield)
- Author Photo (image)
- Photo (media browser)
- Twitter Name (text field)
- Short Description (text area) - @jselt do we need this?
- Description (text area)
- Staff? (boolean)

**Comment by jselt** [comment]
The comps don't show anywhere for a smaller photo or a short bio so I'll leave those out, not sure if we need the twitter name either, maybe on a staff page.
