### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by cfox612** [radcampaign/rad-new#23]
Each service will now have it's own page, we can still do that through the taxonomy, or a basic page. I'm good with either.

Either way the fields will need:
Title
Subtitle
Body/Description
Paragraph
  - Image
  - Subtitle
  - Text area
Paragraph
  - Block Reference (or other layout magic to insert a "start a conversation" block and "web development in our portfolio" view block)

**Comment by jselt** [comment]
Doing as taxonomy so portfolio items can get tagged by service properly.
