### ISSUE TITLE
Homepage Icons

### ISSUE THREAD

**Issue by cfox612** [radcampaign/rad-new#52]
Add region and select 6 icons for row:

- [ ] Defenders
- [ ] Brady
- [ ] WWF
- [ ] Planned Parenthood
- [ ] Clean Water
- [ ] American Heart
- [ ] Now
- [ ] ASCCAN / Pulitzer

**Comment by jselt** [comment]
Is this still a thing? If so, que pasa?

**Comment by cfox612** [comment]
More a list for Allyson

**Comment by jselt** [comment]
k - so leave it open? She doesn't login to Github

**Comment by cfox612** [comment]
I know :) I'll leave that up to @kristinsj

**Comment by kristinsj** [comment]
Okay, closing this here, and adding a line for Allyson in the spreadsheet.
