### ISSUE TITLE
Set up Redirects

### ISSUE THREAD

**Issue by kristinsj** [radcampaign/rad-new#70]
See Redirects Tab in https://docs.google.com/spreadsheets/d/1iPsvxhSEH-QolGauQbKEgxe16QDme64kjblTGXjmwas/edit?usp=sharing

Also attached:

[rad-website-redirects-12-2018.xlsx](https://github.com/radcampaign/rad-new/files/2691814/rad-website-redirects-12-2018.xlsx)

**Comment by jselt** [comment]
http://live-rad-new.pantheonsite.io/admin/config/search/redirect
